#  script.py [-h] [-v|-vv] (--mnist|--svhn|--cifar10|--cifar100|--test-data)
# [--mnist-lenet|--test-model|--cifar10-vgg19|--cifar100-vgg19|--svhn-vgg19]
# --sparsity-factor=int [--nb-iteration-palm=int] [--delta-threshold=float]

all:
#  svhn_log_fac:
#  svhn_log_no_fac:
#  mnist_log_fac:
#  mnist_log_no_fac:
#  cifar10_log_fac:
#  cifar10_log_no_fac:
#  cifar100_log_fac:
  cifar100_log_no_fac:

base:
  sparsity_fac: {"--sparsity-factor": [2, 3, 4, 8, 14]}
  verbosity: ["-v"]
  lr: {"--lr": [1e-3, 1e-4, 1e-5]}
  split: {"--train-val-split": [0.2]}
  epochs: {"--nb-epoch": [10]}
  input_dir: {"--input-dir": ["/gpfsdswork/projects/rech/hpp/ulk32cz/DeployedProjects/palmnet/results/2020/05/3_4_compression_palm_not_log_all"]}
  faust: ["palm"]
  keep_first_or_only_dense: ["--keep-first-layer"]
  only_mask: ["--only-mask"]

no_log_fac:
  base:
  nb_fac: {"--nb-factor": [2, 3]}

log_fac:
  base:
  hierarchical: [""]

cifar100:
  cifar100: ["--cifar100"]
#  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-resnet50-new", "--cifar100-vgg19"]
  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-resnet50-new"]
cifar100_log_fac:
  log_fac:
  cifar100:
cifar100_log_no_fac:
  no_log_fac:
  cifar100:


cifar10:
  cifar100: ["--cifar10"]
  cifar100_vgg19: ["--cifar10-vgg19"]
cifar10_log_fac:
  log_fac:
  cifar10:
cifar10_log_no_fac:
  no_log_fac:
  cifar10:


mnist:
  cifar100: ["--mnist"]
  cifar100_vgg19: ["--mnist-lenet"]
mnist_log_fac:
  log_fac:
  mnist:
mnist_log_no_fac:
  no_log_fac:
  mnist:


svhn:
  svhn: ["--svhn"]
  cifar100_vgg19: ["--svhn-vgg19"]
svhn_log_fac:
  log_fac:
  svhn:
svhn_log_no_fac:
  no_log_fac:
  svhn: