#  script.py [-h] [-v|-vv] (--mnist|--svhn|--cifar10|--cifar100|--test-data)
# [--mnist-lenet|--test-model|--cifar10-vgg19|--cifar100-vgg19|--svhn-vgg19]
# --sparsity-factor=int [--nb-iteration-palm=int] [--delta-threshold=float]

all:
#  svhn_log_fac:
#  svhn_log_no_fac:
#  mnist_log_fac:
#  mnist_log_no_fac:
#  cifar10_log_fac:
#  cifar10_log_no_fac:
#  cifar100_log_fac:
  cifar100_log_no_fac:

act:
  batch_size: {"--batch-size": [128]}
  max_batch_size: {"--max-cum-batch-size": [128]}
  activations: ["--activations"]
  full_net: ["--full-model-approx"]
  onebatch_only: ["--only-one-batch"]
  nb_epoch: {"--nb-epochs": [1]}
#  split: {"--train-val-split": [0.99]}
  nb_iter_palm: {--nb-iteration-palm: [300]}

base:
  sparsity_fac: {"--sparsity-factor": [8]}
#  sparsity_fac_old: {"--sparsity-factor-old": [30]}
  verbosity: ["-v"]
  lr: {"--lr": [1e-3, 1e-4, 1e-5]}
  split: {"--train-val-split": [0.2]}
  epochs: {"--nb-epoch": [10]}
#  baselines_lr: {"--lr-configuration-file": ["/gpfsdswork/projects/rech/hpp/ulk32cz/DeployedProjects/palmnet/parameters/2020/11/finetune_sparse_facto_act.yml"]}
  input_dir: {"--input-dir": ["/linkhome/rech/genzuo01/ulk32cz/wrk/DeployedProjects/palmnet/results/2020/11/10_11_compression_palm_not_log_highK_2step_2ndround"]}
#  base_compressed_model_dir: {"--from-compressed-model": ["/gpfsdswork/projects/rech/hpp/ulk32cz/DeployedProjects/palmnet/results/2020/11/12_13_finetune_palm_not_log_highK_2step"]}
  faust: ["palm"]
  keep_first_or_only_dense: ["--keep-first-layer"]
  multi_step: ["--multi-step"]
#  only_mask: ["--only-mask", ""]
#  seed: {"--seed": [1, 2, 3]}
#  act:

no_log_fac:
  base:
  nb_fac: {"--nb-factor": [2]}
#  nb_fac_old: {"--nb-factor-old": [2]}

log_fac:
  base:
  hierarchical: [""]

cifar100:
  cifar100: ["--cifar100"]
  cifar100_vgg19: ["--cifar100-resnet20-new"]
#  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-vgg19"]
#  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-resnet50-new"]
cifar100_log_fac:
  log_fac:
  cifar100:
cifar100_log_no_fac:
  no_log_fac:
  cifar100:


cifar10:
  cifar100: ["--cifar10"]
  cifar100_vgg19: ["--cifar10-vgg19"]
cifar10_log_fac:
  log_fac:
  cifar10:
cifar10_log_no_fac:
  no_log_fac:
  cifar10:


mnist:
  cifar100: ["--mnist"]
  cifar100_vgg19: ["--mnist-lenet"]
mnist_log_fac:
  log_fac:
  mnist:
mnist_log_no_fac:
  no_log_fac:
  mnist:


svhn:
  svhn: ["--svhn"]
  cifar100_vgg19: ["--svhn-vgg19"]
svhn_log_fac:
  log_fac:
  svhn:
svhn_log_no_fac:
  no_log_fac:
  svhn: