#  script.py [-h] [-v|-vv] (--mnist|--svhn|--cifar10|--cifar100|--test-data)
# [--mnist-lenet|--test-model|--cifar10-vgg19|--cifar100-vgg19|--svhn-vgg19]
# --sparsity-factor=int [--nb-iteration-palm=int] [--delta-threshold=float]

all:
#  svhn_log_fac:
#  svhn_log_no_fac:
#  mnist_log_fac:
  mnist_log_no_fac:
  mnist_log_no_fac_act:
#  cifar10_log_fac:
#  cifar10_log_no_fac:
#  cifar100_log_fac:
  cifar100_log_no_fac:
  cifar100_log_no_fac_act:

base:
  sparsity_fac: {"--sparsity-factor": [3]}
  verbosity: ["-v"]
  faust: ["palm"]
#  seed: {"--seed": [1, 2, 3]}
  split: {"--train-val-split": [0.9]}


act:
  batch_size: {"--batch-size": [50, 100, 128]}
  max_batch_size: {"--max-cum-batch-size": [128]}
  activations: ["--activations"]
  nb_epoch: {"--nb-epochs": [1, 2, 3]}
  nb_iter_palm: {--nb-iteration-palm: [5, 10, 50]}

no_log_fac:
  base:
  nb_fac: {"--nb-factor": [3]}

log_fac:
  base:
  hierarchical: [""]

cifar100:
  cifar100: ["--cifar100"]
#  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-resnet50-new", "--cifar100-vgg19"]
  cifar100_vgg19: ["--cifar100-resnet20-new", "--cifar100-vgg19"]
cifar100_log_fac:
  log_fac:
  cifar100:
cifar100_log_no_fac:
  no_log_fac:
  cifar100:
cifar100_log_no_fac_act:
  cifar100_log_no_fac:
  act:

cifar10:
  cifar100: ["--cifar10"]
  cifar100_vgg19: ["--cifar10-vgg19"]
cifar10_log_fac:
  log_fac:
  cifar10:
cifar10_log_no_fac:
  no_log_fac:
  cifar10:


mnist:
  cifar100: ["--mnist"]
  cifar100_vgg19: ["--mnist-lenet"]
mnist_log_fac:
  log_fac:
  mnist:
mnist_log_no_fac:
  no_log_fac:
  mnist:
mnist_log_no_fac_act:
  mnist_log_no_fac:
  act:


svhn:
  svhn: ["--svhn"]
  cifar100_vgg19: ["--svhn-vgg19"]
svhn_log_fac:
  log_fac:
  svhn:
svhn_log_no_fac:
  no_log_fac:
  svhn: